### ISSUE TITLE
Issue with links and videos following embedded video

### ISSUE THREAD

**Issue by thomashardy** [maur1th/naxos-forum#47]
**Context:**

An embedded video within a post deactivates the links and/or other videos that follow it.

**Steps to reproduce:**

1. Create/edit a post.
2. Add a video within the post using the [video] tag.
3. Below the embedded video, add a link using the [url] tag (and/or another video).
4. Submit/preview the post.

**Actual results:**

- The video is embedded correctly, but the URL is displayed just below the video. The URL contains the smiley :/ due to incorrect interpretation of the https**:/**/ part of the URL.
- Links and videos added below the embedded video do not work. They work if added before the first embedded video.

**Expected results:**

- The URL of the first embedded video should not be displayed in the post.
- Links and/or other embedded videos posted after the first embedded video should work normally.

Post ID example to see the bug: 1499680

**Comment by maur1th** [comment]
Fixed with https://github.com/maur1th/naxos-forum/commit/fb0b0022a9ed9170b401cd19da975685da9e79a3. Please reopen if you still encounter the issue!
