### ISSUE TITLE
Search results pagination is broken

### ISSUE THREAD

**Issue by thomashardy** [maur1th/naxos-forum#73]
After a search, only the first page results are viewable, we can't see the other pages of results through the pagination.

**Steps to reproduce:**

- Do a search on the forum which is significant to return several pages of results
- Try to navigate to another page

https://i.imgur.com/5IZ2Kxg.png

**Actual results:**

You can't go to another page and see the other search results

**Expected results:**

You should be able to navigate through the pagination of the search results

**Comment by thomashardy** [comment]
There is an encoding issue within the returned URL after a search, the character `&` which is used to indicate another page is converted into HTML `&amp`.

Example for the search "blabla":

- Page1: `search/?q=post%3Ablabla`
- Clic for the page2: `search/?q=post%3Ablabla&amp;page=2`
- If we manually remove the `amp` to get `search/?q=post%3Ablabla`&page=2` we can access the page 2

(see FoRuM post 1592817 for morel details)

**Comment by maur1th** [comment]
fixed with https://github.com/maur1th/naxos-forum/commit/7fe9201b5886d336563b8a01d5ff6a0be46ce61d
